package C868.Entities;

/**
 * This is the class for the Country object
 * @author Patrick Denney
 */
public class Country {
    private final int countryID;
    private String countryName;
    private String createdDate;
    private String createdBy;
    private String lastUpdated;
    private String lastUpdatedBy;

    /**
     * This is the constructor method for the Country object
     * @param countryID ID number generated by the database
     * @param countryName name of the country
     */
    public Country(int countryID, String countryName){
        this.countryID = countryID;
        this.countryName = countryName;
    }

    /**
     *
     * @return Returns the ID number for the country
     */
    public int getCountryID() {
        return countryID;
    }

    /**
     *
     * @return Returns the name of the country
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the name of the country
     * @param countryName
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    /**
     *
     * @return Returns the date and time that the country was added to the database
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the date and time that the country was added to the database
     * @param createdDate The date and time that the country was added to the database
     */
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    /**
     *
     * @return Returns the user who created the country record in the database
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the user who created the country record in the database
     * @param createdBy
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     *
     * @return Returns the date and time that the country record was updated in the database
     */
    public String getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Sets the date and time that the country record was updated in the database
     * @param lastUpdated
     */
    public void setLastUpdated(String lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     *
     * @return Returns the user who last updated the country record in the database
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * Sets the user who last updated the country record in the database
     * @param lastUpdatedBy
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
}
