package C868.Entities;

/**
 * This is the class for the First Level divisions
 * @author Patrick Denney
 */
public class FLDivision {
    private int divisionID;
    private String division;
    private String createdDate;
    private String createdBy;
    private String lastUpdated;
    private String lastUpdatedBy;
    private int countryID;//fk

    /**
     * This is the constructor method for the FLDivision class
     * @param divId ID number generated by the database
     * @param divName name of the Division
     */
    public FLDivision(int divId, String divName) {
        this.divisionID = divId;
        this.division = divName;
    }

    /**
     *
     * @return Returns the ID number
     */
    public int getDivisionID() {
        return divisionID;
    }

    /**
     *
     * @return Returns the division name
     */
    public String getDivision() {
        return division;
    }

    /**
     * Sets the division name
     * @param division
     */
    public void setDivision(String division) {
        this.division = division;
    }

    /**
     *
     * @return Returns the date and time that the record was created
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the date and time that the record was created
     * @param createdDate
     */
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    /**
     *
     * @return Returns the user who created the record
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets user who created the record
     * @param createdBy
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     *
     * @return Returns date and time that record was last updated
     */
    public String getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Sets date and time that record was last updated
     * @param lastUpdated
     */
    public void setLastUpdated(String lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     *
     * @return Returns user who last updated the record
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * Sets user who last updated the record
     * @param lastUpdatedBy
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     *
     * @return Returns the country ID
     */
    public int getCountryID() {
        return countryID;
    }

}
