package C868.Entities;

/**
 * This is the class for the User object
 */
public class User {
    private int userID;
    private String userName;
    private String password;
    private String createdDate;
    private String createdBy;
    private String lastUpdate;
    private String lastUpdatedBy;

    /**
     * This is the constructor method for the User object
     * @param userID ID number generated by the database
     * @param userName user's name
     * @param password user's password
     * @param createdDate date and time user's record was created
     * @param createdBy user who created user's record
     * @param lastUpdate date and time user's record was last updated
     * @param lastUpdatedBy user who last updated the user's record
     */
    public User(int userID, String userName, String password, String createdDate, String createdBy, String lastUpdate, String lastUpdatedBy) {
        this.userID = userID;
        this.userName = userName;
        this.password = password;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.lastUpdate = lastUpdate;
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     *
     * @return Returns user ID
     */
    public int getUserID() {
        return userID;
    }

    /**
     * Sets user ID
     * @param userID
     */
    public void setUserID(int userID) {
        this.userID = userID;
    }

    /**
     *
     * @return Returns user's name
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets user's name
     * @param userName
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     *
     * @return Returns user's password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets user's password
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     *
     * @return Returns date and time that user's record was created
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets date and time that user's record was created
     * @param createdDate
     */
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    /**
     *
     * @return Returns user who created user's record
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets user who created user's record
     * @param createdBy
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     *
     * @return Returns date and time that the user's record was updated
     */
    public String getLastUpdate() {
        return lastUpdate;
    }

    /**
     * Sets date and time that the user's record was updated
     * @param lastUpdate
     */
    public void setLastUpdate(String lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     *
     * @return Returns the user that last update the user's record
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * Sets the user that last update the user's record
     * @param lastUpdatedBy
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
}
